local tileMain = THEME:GetPathG("tile",GAMESTATE:GetCurrentStage(GAMESTATE:GetMasterPlayerNumber()).."_main");
local tileBack = THEME:GetPathG("tile",GAMESTATE:GetCurrentStage(GAMESTATE:GetMasterPlayerNumber()).."_back");

return Def.ActorFrame{
	OnCommand=cmd(Center);
	Def.ActorFrame{
		OnCommand=cmd(y,-192);
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,-96);
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(diffusealpha,0;sleep,.234;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
	};
	Def.ActorFrame{
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.234;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(diffusealpha,0;sleep,.301;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.234;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,96);
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(diffusealpha,0;sleep,.234;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,192);
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
	};
}