local tileMain = THEME:GetPathG("tile",GAMESTATE:GetCurrentStage(GAMESTATE:GetMasterPlayerNumber()).."_main");
local tileBack = THEME:GetPathG("tile",GAMESTATE:GetCurrentStage(GAMESTATE:GetMasterPlayerNumber()).."_back");

return Def.ActorFrame{
	OnCommand=cmd(Center);
	Def.ActorFrame{
		OnCommand=cmd(y,-192);
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-384);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-256);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-128);
		};
		LoadActor(tileMain);
		LoadActor(tileBack)..{
			OnCommand=cmd(x,128);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,256);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,384);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,-96);
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-384);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-256);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-128);
		};
		LoadActor(tileBack);
		LoadActor(tileMain)..{
			OnCommand=cmd(x,128);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,256);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,384);
		};
	};
	Def.ActorFrame{
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-384);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-256);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-128);
		};
		LoadActor(tileMain);
		LoadActor(tileBack)..{
			OnCommand=cmd(x,128);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,256);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,384);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,96);
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-384);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-256);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-128);
		};
		LoadActor(tileBack);
		LoadActor(tileMain)..{
			OnCommand=cmd(x,128);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,256);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,384);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,192);
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-384);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,-256);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,-128);
		};
		LoadActor(tileMain);
		LoadActor(tileBack)..{
			OnCommand=cmd(x,128);
		};
		LoadActor(tileMain)..{
			OnCommand=cmd(x,256);
		};
		LoadActor(tileBack)..{
			OnCommand=cmd(x,384);
		};
	};
}