return Def.ActorFrame{
	OnCommand=cmd(Center;sleep,1);
	Def.Quad{
		OnCommand=cmd(FullScreen;addx,-SCREEN_WIDTH/2;addy,-SCREEN_HEIGHT/2;diffuse,color("#000000");diffusealpha,0;linear,.3;diffusealpha,.8);
	};
	Def.ActorFrame{
		OnCommand=cmd(y,-192);
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,-96);
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,0;sleep,.234;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
	};
	Def.ActorFrame{
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.234;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,0;sleep,.301;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.234;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,96);
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,0;sleep,.234;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,192);
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,0;sleep,.167;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,0;sleep,.1;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,0;sleep,.034;diffusealpha,1);
		};
	};
}