return Def.ActorFrame{
	OnCommand=cmd(Center);
	Def.ActorFrame{
		OnCommand=cmd(y,-192);
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,1;sleep,.167;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,-96);
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,1;sleep,.167;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,1;sleep,.1;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,1;sleep,.167;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
	};
	Def.ActorFrame{
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,1;sleep,.167;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,1;sleep,.1;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,1;sleep,.034;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,1;sleep,.1;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,1;sleep,.167;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,96);
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,1;sleep,.167;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,1;sleep,.1;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,1;sleep,.167;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
	};
	Def.ActorFrame{
		OnCommand=cmd(y,192);
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-384;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-256;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,-128;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(diffusealpha,1;sleep,.167;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,128;diffusealpha,1;sleep,.234;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,256;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("welcome","tile"))..{
			OnCommand=cmd(x,384;diffusealpha,1;sleep,.301;diffusealpha,0);
		};
	};
}